### ISSUE TITLE
发现了一个bug。

### ISSUE THREAD

**Issue by justcodingnobb** [wangjinglian/DFA#1]
如果过滤sentence只有一个字或者匹配的敏感词库只有一个时候

用户词语长度为1 ：
问题：curState.nodes为空，肯定不会走替换逻辑
纠正： 在for里面判断curState.nodes是否为空，为空直接替换

敏感词库长度为1：
问题：判断完m[w]之后，不会走for的逻辑 因为长度是等于不是小于
纠正：j <= len

**Comment by GGhuaxina** [comment]
感谢纠正  :-)
